name: Daily Newsletter
on:
  schedule:
    - cron: '0 0 * * 1-5'  # 평일(월-금) 오전 9시 (UTC 0시)

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Newsletter API
        run: |
          curl -X GET "https://koreamedinfo.vercel.app/api/cron/send-news?key=${{ secrets.NEWSLETTER_CRON_KEY }}"
