name: Daily Newsletter
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 UTC 00:00 (한국 시간 09:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Send Newsletter
        run: |
          curl -X GET ${{ secrets.NEWSLETTER_API_URL }} \
          -H "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}"
        env:
          NEWSLETTER_API_URL: ${{ secrets.NEWSLETTER_API_URL }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }} 